/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface BarnMockInterface extends ethers.utils.Interface {
  functions: {
    "callRegisterDeposit(address,uint256)": FunctionFragment;
    "callRegisterWithdrawal(address,uint256)": FunctionFragment;
    "r()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "callRegisterDeposit",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "callRegisterWithdrawal",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "r", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "callRegisterDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callRegisterWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "r", data: BytesLike): Result;

  events: {};
}

export class BarnMock extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: BarnMockInterface;

  functions: {
    callRegisterDeposit(
      user: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "callRegisterDeposit(address,uint256)"(
      user: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    callRegisterWithdrawal(
      user: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "callRegisterWithdrawal(address,uint256)"(
      user: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    r(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "r()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;
  };

  callRegisterDeposit(
    user: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "callRegisterDeposit(address,uint256)"(
    user: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callRegisterWithdrawal(
    user: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "callRegisterWithdrawal(address,uint256)"(
    user: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  r(overrides?: CallOverrides): Promise<string>;

  "r()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    callRegisterDeposit(
      user: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "callRegisterDeposit(address,uint256)"(
      user: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    callRegisterWithdrawal(
      user: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "callRegisterWithdrawal(address,uint256)"(
      user: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    r(overrides?: CallOverrides): Promise<string>;

    "r()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    callRegisterDeposit(
      user: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "callRegisterDeposit(address,uint256)"(
      user: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    callRegisterWithdrawal(
      user: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "callRegisterWithdrawal(address,uint256)"(
      user: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    r(overrides?: CallOverrides): Promise<BigNumber>;

    "r()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    callRegisterDeposit(
      user: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "callRegisterDeposit(address,uint256)"(
      user: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    callRegisterWithdrawal(
      user: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "callRegisterWithdrawal(address,uint256)"(
      user: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    r(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "r()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
