/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DiamondCutFacetInterface extends ethers.utils.Interface {
  functions: {
    "c_0xc0121af6(bytes32)": FunctionFragment;
    "diamondCut(tuple[],address,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "c_0xc0121af6",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "diamondCut",
    values: [
      {
        facetAddress: string;
        action: BigNumberish;
        functionSelectors: BytesLike[];
      }[],
      string,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "c_0xc0121af6",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "diamondCut", data: BytesLike): Result;

  events: {
    "DiamondCut(tuple[],address,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DiamondCut"): EventFragment;
}

export class DiamondCutFacet extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DiamondCutFacetInterface;

  functions: {
    c_0xc0121af6(
      c__0xc0121af6: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;

    "c_0xc0121af6(bytes32)"(
      c__0xc0121af6: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;

    diamondCut(
      _diamondCut: {
        facetAddress: string;
        action: BigNumberish;
        functionSelectors: BytesLike[];
      }[],
      _init: string,
      _calldata: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "diamondCut(tuple[],address,bytes)"(
      _diamondCut: {
        facetAddress: string;
        action: BigNumberish;
        functionSelectors: BytesLike[];
      }[],
      _init: string,
      _calldata: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  c_0xc0121af6(
    c__0xc0121af6: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  "c_0xc0121af6(bytes32)"(
    c__0xc0121af6: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  diamondCut(
    _diamondCut: {
      facetAddress: string;
      action: BigNumberish;
      functionSelectors: BytesLike[];
    }[],
    _init: string,
    _calldata: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "diamondCut(tuple[],address,bytes)"(
    _diamondCut: {
      facetAddress: string;
      action: BigNumberish;
      functionSelectors: BytesLike[];
    }[],
    _init: string,
    _calldata: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    c_0xc0121af6(
      c__0xc0121af6: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "c_0xc0121af6(bytes32)"(
      c__0xc0121af6: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    diamondCut(
      _diamondCut: {
        facetAddress: string;
        action: BigNumberish;
        functionSelectors: BytesLike[];
      }[],
      _init: string,
      _calldata: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "diamondCut(tuple[],address,bytes)"(
      _diamondCut: {
        facetAddress: string;
        action: BigNumberish;
        functionSelectors: BytesLike[];
      }[],
      _init: string,
      _calldata: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    DiamondCut(_diamondCut: null, _init: null, _calldata: null): EventFilter;
  };

  estimateGas: {
    c_0xc0121af6(
      c__0xc0121af6: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "c_0xc0121af6(bytes32)"(
      c__0xc0121af6: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    diamondCut(
      _diamondCut: {
        facetAddress: string;
        action: BigNumberish;
        functionSelectors: BytesLike[];
      }[],
      _init: string,
      _calldata: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "diamondCut(tuple[],address,bytes)"(
      _diamondCut: {
        facetAddress: string;
        action: BigNumberish;
        functionSelectors: BytesLike[];
      }[],
      _init: string,
      _calldata: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    c_0xc0121af6(
      c__0xc0121af6: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "c_0xc0121af6(bytes32)"(
      c__0xc0121af6: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    diamondCut(
      _diamondCut: {
        facetAddress: string;
        action: BigNumberish;
        functionSelectors: BytesLike[];
      }[],
      _init: string,
      _calldata: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "diamondCut(tuple[],address,bytes)"(
      _diamondCut: {
        facetAddress: string;
        action: BigNumberish;
        functionSelectors: BytesLike[];
      }[],
      _init: string,
      _calldata: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
