/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { LibDiamondStorage } from "./LibDiamondStorage";

export class LibDiamondStorageFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<LibDiamondStorage> {
    return super.deploy(overrides || {}) as Promise<LibDiamondStorage>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): LibDiamondStorage {
    return super.attach(address) as LibDiamondStorage;
  }
  connect(signer: Signer): LibDiamondStorageFactory {
    return super.connect(signer) as LibDiamondStorageFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LibDiamondStorage {
    return new Contract(address, _abi, signerOrProvider) as LibDiamondStorage;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "c__0x508c7685",
        type: "bytes32",
      },
    ],
    name: "c_0x508c7685",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x60e0610025600b82828239805160001a60731461001857fe5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c8063fa72c4cd146038575b600080fd5b604e6004803603810190604a91906066565b6050565b005b50565b6000813590506060816096565b92915050565b600060208284031215607757600080fd5b60006083848285016053565b91505092915050565b6000819050919050565b609d81608c565b811460a757600080fd5b5056fea2646970667358221220167251ba202b52441a847fd30800dd56800b8c29c242b63ec3ce76cbfc2490b764736f6c63430007030033";
