/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface LibDiamondInterface extends ethers.utils.Interface {
  functions: {
    "c_0xfcecf9b4(bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "c_0xfcecf9b4",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "c_0xfcecf9b4",
    data: BytesLike
  ): Result;

  events: {
    "DiamondCut(tuple[],address,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DiamondCut"): EventFragment;
}

export class LibDiamond extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: LibDiamondInterface;

  functions: {
    c_0xfcecf9b4(
      c__0xfcecf9b4: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;

    "c_0xfcecf9b4(bytes32)"(
      c__0xfcecf9b4: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;
  };

  c_0xfcecf9b4(
    c__0xfcecf9b4: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  "c_0xfcecf9b4(bytes32)"(
    c__0xfcecf9b4: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    c_0xfcecf9b4(
      c__0xfcecf9b4: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "c_0xfcecf9b4(bytes32)"(
      c__0xfcecf9b4: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    DiamondCut(_diamondCut: null, _init: null, _calldata: null): EventFilter;
  };

  estimateGas: {
    c_0xfcecf9b4(
      c__0xfcecf9b4: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "c_0xfcecf9b4(bytes32)"(
      c__0xfcecf9b4: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    c_0xfcecf9b4(
      c__0xfcecf9b4: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "c_0xfcecf9b4(bytes32)"(
      c__0xfcecf9b4: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
