/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { LibOwnership } from "./LibOwnership";

export class LibOwnershipFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<LibOwnership> {
    return super.deploy(overrides || {}) as Promise<LibOwnership>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): LibOwnership {
    return super.attach(address) as LibOwnership;
  }
  connect(signer: Signer): LibOwnershipFactory {
    return super.connect(signer) as LibOwnershipFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LibOwnership {
    return new Contract(address, _abi, signerOrProvider) as LibOwnership;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "c__0x18bf97e4",
        type: "bytes32",
      },
    ],
    name: "c_0x18bf97e4",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x60e0610025600b82828239805160001a60731461001857fe5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c8063901e259f146038575b600080fd5b604e6004803603810190604a91906066565b6050565b005b50565b6000813590506060816096565b92915050565b600060208284031215607757600080fd5b60006083848285016053565b91505092915050565b6000819050919050565b609d81608c565b811460a757600080fd5b5056fea2646970667358221220f5fbe08d023fdebe87f2fdf5d8f6a8ee5a3b6850d9c8e50fc7cdb05f871efbd864736f6c63430007030033";
