/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface Test2FacetInterface extends ethers.utils.Interface {
  functions: {
    "c_0xfb799b00(bytes32)": FunctionFragment;
    "test1Func1()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "c_0xfb799b00",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "test1Func1",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "c_0xfb799b00",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "test1Func1", data: BytesLike): Result;

  events: {};
}

export class Test2Facet extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: Test2FacetInterface;

  functions: {
    c_0xfb799b00(
      c__0xfb799b00: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;

    "c_0xfb799b00(bytes32)"(
      c__0xfb799b00: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;

    test1Func1(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "test1Func1()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;
  };

  c_0xfb799b00(
    c__0xfb799b00: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  "c_0xfb799b00(bytes32)"(
    c__0xfb799b00: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  test1Func1(overrides?: CallOverrides): Promise<BigNumber>;

  "test1Func1()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    c_0xfb799b00(
      c__0xfb799b00: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "c_0xfb799b00(bytes32)"(
      c__0xfb799b00: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    test1Func1(overrides?: CallOverrides): Promise<BigNumber>;

    "test1Func1()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    c_0xfb799b00(
      c__0xfb799b00: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "c_0xfb799b00(bytes32)"(
      c__0xfb799b00: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    test1Func1(overrides?: CallOverrides): Promise<BigNumber>;

    "test1Func1()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    c_0xfb799b00(
      c__0xfb799b00: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "c_0xfb799b00(bytes32)"(
      c__0xfb799b00: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    test1Func1(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "test1Func1()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
