/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { Test2Facet } from "./Test2Facet";

export class Test2FacetFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<Test2Facet> {
    return super.deploy(overrides || {}) as Promise<Test2Facet>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Test2Facet {
    return super.attach(address) as Test2Facet;
  }
  connect(signer: Signer): Test2FacetFactory {
    return super.connect(signer) as Test2FacetFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Test2Facet {
    return new Contract(address, _abi, signerOrProvider) as Test2Facet;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "c__0xfb799b00",
        type: "bytes32",
      },
    ],
    name: "c_0xfb799b00",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "test1Func1",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061014e806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806319e3b5331461003b578063cedaf98f14610059575b600080fd5b610043610087565b6040518082815260200191505060405180910390f35b6100856004803603602081101561006f57600080fd5b8101908080359060200190929190505050610115565b005b60006100b57f3925ae2846e9965f08c79f8984a8002590fcbdd9a807bf1cf3ad81189c520d1060001b610115565b6100e17f655214ea453a0095275ce22be004e89459a9049aaafa1ee967198e2af91b442760001b610115565b61010d7f5035a2a742737c750bc90f1f12abf47901c5da5990a2b6f56736598a9a1a103360001b610115565b6104d2905090565b5056fea2646970667358221220ae35410d5ccc587dee3bf5b00a2ec8dc5b8c2a891bab7a50c8d5c4f56b1da5bd64736f6c63430007030033";
